FROM node:17

RUN apt-get install -y git

WORKDIR /usr/src/app

RUN git clone https://github.com/keikaavousi/fake-store-api .

RUN git checkout d03d27d

RUN npm install

EXPOSE $PORT

CMD [ "node", "server.js" ]
